# Generated by Django 5.1.1 on 2024-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('max_incorrect_guesses', models.IntegerField()),
                ('state', models.CharField(choices=[('InProgress', 'In Progress'), ('Won', 'Won'), ('Lost', 'Lost')], default='InProgress', max_length=20)),
            ],
        ),
    ]
