# Generated by Django 5.1.1 on 2024-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guessed_letters',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(default='InProgress', max_length=50),
        ),
    ]
